### ISSUE TITLE
Include # in codes shown under colors?

### ISSUE THREAD

**Issue by TJScalzo** [edelstone/tints-and-shades#13] opened 2019-10-15 16:41 UTC
It's kind of misleading to show just the code because when you copy a color it includes the #. I think it would make more sense to show the code exactly as it will be copied.

**Comment by edelstone** [comment] 2019-10-15 19:12
Another way to ask this @TJScalzo - should the copy necessarily include the `#` sign to begin with? I didn't have an opinion on that when the contribution was made, so I left it.

**Comment by TJScalzo** [comment] 2019-10-15 20:41
It's a tough question to answer. The input for the generator doesn't require you to include the `#` when entering colors. But when you actually go to use a color you're going to need it. Regardless, I think whatever gets copied should match what is shown below the color's cell.

**Comment by edelstone** [comment] 2019-10-15 20:50
I've noticed that I often don't want the hashtag because I'm pasting it somewhere a hashtag already exists, like the below GIF. Just so happens that when you click in to a hex code in my code editor, it ignores the hashtag (not sure if that's entirely common, but I think it is).

![s1jIaWOQMb](https://user-images.githubusercontent.com/8269046/66868668-5d710700-ef63-11e9-812f-2f866a224010.gif)

I lean towards removing the hashtag from the copy simply because adding a bunch of hashtags to the table will clutter it up.

**Example:**

<img width="1258" alt="Screen Shot 2019-10-15 at 3 57 12 PM" src="https://user-images.githubusercontent.com/8269046/66869228-8645cc00-ef64-11e9-9340-f2040132530c.png">

**Comment by AleksandrHovhannisyan** [comment] 2020-03-21 23:30
@edelstone How about removing the hashtags from the table but adding a checkbox along the lines of `Include hashtag on copy` to make it optional?

**Comment by edelstone** [comment] 2020-03-22 00:38
Thanks for the reply @AleksandrHovhannisyan.

Right now there are no hashtags visible in the text or transferred in a copy action.

Are you suggesting a site-wide setting that allows the user to specify if they want a hashtag on copy?

**Comment by AleksandrHovhannisyan** [comment] 2020-03-22 11:53
@edelstone Yup! Visually, the table would remain without hashtags. But if a user checks that checkbox, then the copy action would prepend a hashtag to whatever hex code is being copied (behind the scenes—we still wouldn't have to render any hashtags).

**Comment by edelstone** [comment] 2020-03-22 13:38
@AleksandrHovhannisyan So do you see this checkbox existing in a common, global place? For example, click a ⚙️ icon somewhere in the interface and a dialog opens showing preference options. In this case there is one option: to tick a box for hashtag on/off when copying. And then presumably we are able to save this preference for them until they clear their cache.

Or perhaps were you saying that there should be a checkbox that exists somewhere in the vicinity of the copy button that appears after they click the copy button?

Or something else entirely?

I will add that such a thing is probably beyond my capabilities of implementing, but I'm happy to design the UX and we can create an open issue and try to attract some assistance.

**Comment by AleksandrHovhannisyan** [comment] 2020-03-22 14:10
I threw together a quick mock to make my idea clearer:

![image](https://user-images.githubusercontent.com/19352442/77251496-0a436480-6c25-11ea-9998-97462ab84f01.png)

Thoughts?

I imagine this will be difficult because we have a separate script for the clipboard copying logic. If we write our own function to handle clipboard copying, we could listen for input on the checkbox and set a flag in the script (e.g., `shouldCopyWithHashtag`) that we check in the copy routine. True? Prepend a hashtag. False? Just copy the code.

**Comment by edelstone** [comment] 2020-03-22 14:26
OK thanks for that - I understand now, and from a usability perspective I think it's pretty clear what this does. I would maybe tweak the wording a little, but the placement is good. I'm thinking this would be visible even before the color table appears, so it would be on-screen all the time.

As far as implementation, I don't really have much of an opinion on that as long as it works. Obviously I lean towards simplicity and speed, and no regressions from a UX perspective.

I'll reopen this issue. Feel free to give it a shot if it's something you'd like to do - no pressure though. I'm happy just having some feedback from you and maybe we'll get some more feedback or volunteer work from others.

**Comment by AleksandrHovhannisyan** [comment] 2020-03-23 15:19
@edelstone Sounds good! I'd like to take a crack at it if that's cool with you.

By the way, I'm on Windows, and when I cloned your repo and opened `index.html`, most of the resources failed to load. I had to remove the forward slash from the stylesheet hrefs, for example: `href="css/normalize.css"` instead of `href="/css/normalize.css"`. 🤷‍♂ 

I can test locally like that and just undo things when I commit, but I figured I'd mention it.

**Comment by edelstone** [comment] 2020-03-23 16:43
@AleksandrHovhannisyan sounds good to me. As long as it’s simple and fast and bug free I’ll push it through. I can always tweak the styles and language later as that’s my wheelhouse; it’s really just the scripts functionality I’ll need completed. 

As far as the trailing slashes, this may have something to do with me using http-server locally for testing. I think it may be temperamental about that - or it may not matter at all. You can go ahead and make the changes that allow the resources to load locally for you, push that feature branch, and then I can pull and check my environment locally to see if it makes any difference. If it does I may ask you to revert that, if not we can merge those changes. 

Happy to have the help! Good luck.

**Comment by AleksandrHovhannisyan** [comment] 2020-03-24 12:40
@edelstone Btw, I'm guessing from the code that you want to support Internet Explorer, right? Wondering if I should avoid using ES6 things like `const` and template literals. Don't want my changes to break your code :)

**Comment by edelstone** [comment] 2020-03-24 12:59
Yeah we definitely want to support as many versions of IE as possible. We have all sorts of users using this in every country.

**Comment by edelstone** [comment] 2020-03-24 13:44
@AleksandrHovhannisyan I see you did a PR, I will have a chance to look at that later today.

I wanted to quickly mention I looked at the recent browser analytics and IE is a pretty small proportion of the users. I think overall I'd prefer not to abandon them, but strangely they do all seem to be from western countries. I'm not sure how much I trust these numbers generally, it's just a single data point.

If you find that your code would be much simpler/faster/etc. using ES6 then use your discretion. Otherwise just leave this PR and I'll check it in a bit.

Here are the stats:

**All browsers last week**
<img width="557" alt="Screen Shot 2020-03-24 at 8 38 37 AM" src="https://user-images.githubusercontent.com/8269046/77431887-53bdbc00-6dab-11ea-8354-9d60087d2045.png">

**IE breakdown over same period**
<img width="688" alt="Screen Shot 2020-03-24 at 8 40 47 AM" src="https://user-images.githubusercontent.com/8269046/77431896-57e9d980-6dab-11ea-9ea4-4bbb7fc13ea1.png">

**Comment by AleksandrHovhannisyan** [comment] 2020-03-24 13:54
We can keep it backwards compatible, no biggie :) I'm just used to ES6 so I didn't want to introduce sneaky breaking changes.

**Closed as completed** 2020-03-24 17:50 UTC
Labels: enhancement, help wanted
